[package]
name = "day01"
version = "0.1.0"
authors = ["Mehmet Denizhan Erdem <denizhan.erdem@checkbox.com.tr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
